config/routes.rb
Rails.application.routes.draw do

     resources :advertisements, :questions

     resources :topics do
          resources :posts, except: [:index]
          resources :sponsored_posts
     end

     resources :posts, only: [] do
          resources :comments, only: [:create, :destroy]
          resources :favorites, only: [:create, :destroy]
          post '/up-vote' => 'votes#up_vote', as: :up_vote
          post '/down-vote' => 'votes#down_vote', as: :down_vote
     end

     #resources :users, only: [:new, :create, :confirm]
     resources :users, :only => [:new, :create, :show] do
          collection do
               post 'confirm'
          end
     end

     resources :sessions, only: [:new, :create, :destroy]

     get 'about' => 'welcome#about'

     root 'welcome#index'
end

app/models/question.rb
class Question < ApplicationRecord
     attribute :title, :string
     attribute :body, :text
     attribute :resolved, :boolean

     has_many :answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
      @questions = Question.all
  end

  def new
      @question = Question.new
  end

  def create
      @question = Question.new
      @question.title = params[:question][:title]
      @question.body = params[:question][:body]
      @question.resolved = params[:question][:resolved]

      if @question.save
          flash[:notice] = "Question was saved."
          redirect_to @question
      else
          flash.now[:alert] = "There was an error saving the question. Please try again."
          render :new
      end
  end

  def show
      @question = Question.find(params[:id])
  end

  def edit
      @question = Question.find(params[:id])
  end

  def update
      @question = Question.find(params[:id])
      @question.title = params[:question][:title]
      @question.body = params[:question][:body]
      @question.resolved = params[:question][:resolved]

      if @question.save
          flash[:notice] = "Question was updated"
          redirect_to @question
      else
          flash.now[:alert] = "There was an error saving the question. Please try again"
          render :edit
      end
  end

  def destroy
      @question = Question.find(params[:id])

      if @question.destroy
          flash[:notice] = "\"#{@question.title}\" was deleted sucessfully."
          redirect_to questions_path
      else
          flash.now[:alert] = "There was an error deleting the question."
          render :show
      end
  end
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<div class="row">
    <div class="col-md-8">
        <%= form_for @question do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
            </div>
            <div class="form-group">
                <%= f.label :resolved %>
                <%= f.check_box :resolved %>
            </div>
            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
</div>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<!--
<div class="col-md-12">
     <%= link_to "New Question", new_question_path, class: 'btn btn-success' %>
 </div>

<% @questions.each do |question| %>
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <%= link_to question.title, question %>
            </h4>
        </div>
    </div>
<% end %>
-->

<div class="row">
     <div class="col-md-8">
          <% @questions.each do |question| %>
              <div class="media">
                  <div class="media-body">
                      <h4 class="media-heading">
                          <%= link_to question.title, question %>
                      </h4>

                      <%= question.answers.count %> Answers
                  </div>
              </div>
          <% end %>
     </div>
     <div class="col-md-4">
          <%= link_to "New Question", new_question_path, class: 'btn btn-success' %>
     </div>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<div class="row">
    <div class="col-md-8">
        <%= form_for @question do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, :required => true, class: 'form-control', placeholder: "Enter question title" %>
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, :required => true, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
            </div>
           <%= f.submit "Save", class: 'btn btn-success' %>
         <% end %>
    </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<div class="row">
    <div class="col-md-8">
        <p><%= @question.body %></p>
        <small>resolved: <%= @question.resolved == true%></small>
    </div>
    <div class="col-md-4">
        <%= link_to "Edit", edit_question_path(@question), class: 'btn btn-success' %>
        <%= link_to "Delete Post", @question, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this question?'} %>
    </div>

</div>

<div class="answers">
     <% @question.answers.each do |answer| %>

          <div class="row">
               <div class="col-md-8">
                    <div class="media">
                         <p>
                              Answer <%= @question.answers.index(answer) + 1 %>: <%= answer.body %>
                         </p>
                    </div>
               </div>
          </div>

     <% end %>
</div>